import { Check, Gauge, IndianRupee, Package, Plus, RefreshCcw, Search, Truck, UserRound, Users, WalletCards } from 'lucide-react';
import { money } from '../data/demo';
import { useAppStore } from '../store';
import { Button, PageHeader, StatCard, Status } from './ui';

export function AdminDashboard() {
  const { data, adminQuery, setAdminQuery, notify } = useAppStore();
  const filteredOrders = data.orders.filter(order => `${order.id} ${order.customer} ${order.address}`.toLowerCase().includes(adminQuery.toLowerCase()));
  const revenue = data.orders.reduce((total, order) => total + order.amount, 0);
  const delivered = data.orders.filter(order => order.status === 'Delivered').length;

  return <>
    <PageHeader eyebrow="Network intelligence · September 2026" title="Welcome back, Admin." copy="Monitor bookings, operations, revenue, and tanker activity across Chennai." action={<div className="heading-actions"><Button variant="quiet" icon={RefreshCcw} onClick={() => notify('Operations dashboard refreshed')}>Refresh</Button><Button variant="primary" icon={Plus} onClick={() => notify('Create order flow opened')}>Create test order</Button></div>} />
    <section className="admin-kpis" aria-label="Network performance"><StatCard icon={IndianRupee} label="Revenue this month" value={money(revenue)} detail="Target ₹1,00,000" tone="highlight" /><StatCard icon={Check} label="Delivered today" value={delivered} detail="2 bookings scheduled" /><StatCard icon={Truck} label="Live tankers" value="12" detail="Active routes" /><StatCard icon={Gauge} label="Fleet utilisation" value="78%" detail="18 vendors online" /></section>
    <section className="admin-kpis secondary" aria-label="Network totals"><StatCard icon={Package} label="Total orders" value={data.orders.length} detail="Water and sewage services" /><StatCard icon={Users} label="Active vendors" value={data.vendors.length} detail="Verified network partners" /><StatCard icon={UserRound} label="Customers" value="1,248" detail="86 new profiles" /><StatCard icon={WalletCards} label="Platform commission" value={money(Math.round(revenue * .1))} detail="10% marketplace share" /></section>
    <div className="admin-grid"><article className="data-surface chart-surface"><div className="section-heading"><div><span className="eyebrow">Order performance · daily flow</span><h2>Water vs sewage orders</h2></div><div className="segmented" role="group" aria-label="Order period"><button className="active" type="button">7 days</button><button type="button">30 days</button><button type="button">90 days</button></div></div><div className="chart" aria-label="Bar chart showing weekly orders">{[52, 68, 43, 75, 61, 88, 70].map((height, index) => <div className="bar-group" key={index}><div className="bars"><i style={{ height: `${height}%` }} /><i style={{ height: `${height * .42}%` }} /></div><small>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][index]}</small></div>)}</div><div className="chart-legend"><span><i className="water" /> Water tanker</span><span><i className="sewage" /> Sewage tanker</span><b>+18.4% vs last week</b></div></article><article className="data-surface"><div className="section-heading"><div><span className="eyebrow">Fleet radar · live</span><h2>Tanker movement</h2></div><Status>Online</Status></div><div className="radar"><b>UT</b><span className="radar-circle c1" /><span className="radar-circle c2" /></div>{data.vendors.map(vendor => <div className="insight" key={vendor.name}><span><Truck size={14} /></span><div><b>{vendor.name}</b><p>{vendor.vehicle} · {vendor.zone} · {vendor.status}</p></div></div>)}</article></div>
    <article className="data-surface table-surface"><div className="table-head"><div><span className="eyebrow">Orders</span><h2>Booking control</h2></div><div className="table-tools"><Button variant="quiet" icon={RefreshCcw} onClick={() => notify('CSV report prepared')}>Export report</Button><label className="input-icon" htmlFor="order-search"><Search size={15} /><input id="order-search" placeholder="Search order or customer" value={adminQuery} onChange={event => setAdminQuery(event.target.value)} /></label></div></div><div className="table-scroll"><table><caption className="sr-only">Urban Tanker booking control</caption><thead><tr><th scope="col">Booking</th><th scope="col">Service</th><th scope="col">Customer</th><th scope="col">Vendor</th><th scope="col">Amount</th><th scope="col">Status</th></tr></thead><tbody>{filteredOrders.map(order => <tr key={order.id}><td><b className="mono">{order.id}</b><small>{order.created}</small></td><td>{order.service}<small>{order.capacity}</small></td><td>{order.customer}<small>{order.address}</small></td><td>{order.vendor}<small>{order.driver}</small></td><td><b>{money(order.amount)}</b><small>{order.payment}</small></td><td><Status>{order.status}</Status></td></tr>)}</tbody></table></div></article>
  </>;
}
